server:
  port: 8066
spring:
  datasource:
    name: datasource1
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: nmca-agent-oldQuan-intf-quan
#cxf路更改
cxf:
  path: "/quan"